name: Release Maven project

on:
  create:
    branches:
      - release/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Extract branch name
        id: extract_branch
        if: ${{ contains(github.ref, 'refs/heads/release') }}
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / - | sed 's/release-*//')" >> $GITHUB_ENV

      - name: Setup Git Email
        run: git config --global user.email "github@stevecrox.github.io"
      - name: Setup Git User
        run: git config --global user.name "GitHub Action"

      - name: Prepare Release with Maven
        if: ${{ contains(github.ref, 'refs/heads/release') }}
        run: mvn --batch-mode --settings .github/maven_settings.xml release:prepare -DreleaseVersion=${{ env.BRANCH_NAME }} -Dgoals=clean package org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign net.nicoulaj.maven.plugins:checksum-maven-plugin:1.11:artifacts deploy -DattachChecksums=true
        env:
          OSSRH_USER: ${{ secrets.SCM_USER }}
          OSSRH_TOKEN: ${{ secrets.SCM_TOKEN }}
          GITHUB_USER: ${{ secrets.RELEASE_USER }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GPG_KEY_ID: ${{ secrets.GPG_PRIVATE_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          
      - name: Release with Maven
        if: ${{ contains(github.ref, 'refs/heads/release') }}
        run: mvn --batch-mode --settings .github/maven_settings.xml release:perform -DreleaseVersion=${{ env.BRANCH_NAME }} -Dgoals=clean package org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign net.nicoulaj.maven.plugins:checksum-maven-plugin:1.11:artifacts deploy -DattachChecksums=true
        env:
          OSSRH_USER: ${{ secrets.SCM_USER }}
          OSSRH_TOKEN: ${{ secrets.SCM_TOKEN }}
          GITHUB_USER: ${{ secrets.RELEASE_USER }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GPG_KEY_ID: ${{ secrets.GPG_PRIVATE_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

      - name: Merge Release branch into Main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: release/${{ env.BRANCH_NAME }}
          target_branch: main
          github_token: ${{ secrets.RELEASE_TOKEN }}
